name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node via .nvmrc (uses Corepack-compatible Node)
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          check-latest: true
          cache: 'yarn'

      - name: Enable Corepack
        run: corepack enable

      - name: Use Yarn version defined in package.json
        run: corepack prepare $(node -p "require('./package.json').packageManager") --activate

      - name: Verify Yarn version
        run: yarn --version

      - name: Install dependencies (immutable)
        run: yarn install --immutable

      - name: Type Check
        run: yarn typecheck

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build