name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build, Lint & Typecheck
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node version from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Enable Corepack
        run: corepack enable

      - name: Activate Yarn version from package.json
        run: corepack prepare $(jq -r '.packageManager' package.json) --activate
        shell: bash

      - name: Verify Yarn version
        run: yarn --version

      - name: Install dependencies (immutable)
        run: yarn install --immutable

      - name: Type Check
        run: yarn typecheck

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build